# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ffc4b3ee8b47fbc9e8bba24fe3b8c07880c373f90083f74838afcf26b3cfd798d0f3864f3d2c2190a1e6c399a9b4fb5b5a0c230c4922fc342337796d786eee

test:
  secret_key_base: 52679e6f9f833755c79839a72b25d9aa9ce0ee48d705d4e75a8844ace01340863d9e92b4ba15b315bf6f8772295740314df0d6f652419b10d3bd401bb83b0fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
